package com.kaetsu.gamelist.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GenerationType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;

import java.util.Objects;

// Annotate the class with @Entity to indicate that it is a JPA entity
@Entity
// Annotate the class with @Table and specify the name of the table
@Table(name = "tb_games")
public class Game {

    // Annotate the id field with @Id to indicate that it is the primary key
    @Id
    // Annotate the id field with @GeneratedValue to indicate that it is auto-generated by the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;

    // Annotate the year field with @Column and specify the name of the column on DB, this is necessary because year is a reserved word in SQL
    @Column(name = "game_year")
    private Integer year;
    private String genre;
    private String platforms;
    private Double score;

    @Column(name = "img_url")
    private String imgURL;
    
    // Annotate the descriptions fields for explicit TEXT type in DB, default is VARCHAR with only 255 chars limit
    @Column(columnDefinition = "TEXT")
    private String shortDescription;
    @Column(columnDefinition = "TEXT")
    private String longDescription;

    public Game() {
    }

    public Game(String longDescription, String shortDescription, Long id, String title, Integer year, String genre, String platforms, String imgUR, Double score) {
        this.longDescription = longDescription;
        this.shortDescription = shortDescription;
        this.id = id;
        this.title = title;
        this.year = year;
        this.genre = genre;
        this.platforms = platforms;
        this.imgURL = imgURL;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public String getLongDescription() {
        return longDescription;
    }

    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription;
    }

    public String getImgURL() {
        return imgURL;
    }

    public void setImgURL(String imgURL) {
        this.imgURL = imgURL;
    }

    public String getplatforms() {
        return platforms;
    }

    public void setplatforms(String platforms) {
        this.platforms = platforms;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    } 

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Game game = (Game) o;
        return Objects.equals(id, game.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

}
